version: '3.8'

services:
  squid-proxy:
    image: ubuntu/squid:latest
    container_name: squid_lab_cisco
    ports:
      - "3128:3128"
    volumes:
      - ./config/squid.conf:/etc/squid/squid.conf
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# Instrucciones de uso:
# 1. cd 04_Network_Security_Infrastructure/docker
# 2. docker-compose up -d
# 3. Configura tu navegador para usar 127.0.0.1:3128 como proxy.
# 4. Para ver logs en vivo: docker logs -f squid_lab_cisco
