version: '3.8'

services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: dns_lab_tema3
    environment:
      - BIND9_USER=root
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind
    restart: unless-stopped

# Instrucciones:
# 1. Ejecuta 'docker-compose up -d' dentro de esta carpeta.
# 2. Configura tu terminal para usar este DNS: 'nslookup target.local 127.0.0.1'
