services:
  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: cisco_dvwa
    restart: unless-stopped
    ports:
      - "127.0.0.1:80:80"
    environment:
      - PHP_TZ=Europe/Madrid
      - MYSQL_ROOT_PASSWORD=toor
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - vulnnet
    deploy:
      resources:
        limits:
          memory: 512M

  juiceshop:
    image: bkimminich/juice-shop:latest
    container_name: cisco_juiceshop
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - vulnnet
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  vulnnet:
    driver: bridge
